app/api/urls.py
# myapi/urls.py
from django.urls import include, path
from rest_framework.authtoken import views
from . import views as main_view


urlpatterns = [
    path('agent_upload/', main_view.api_upload_agent_results, name="agent_upload"),
    path('heartbeat/', main_view.api_heartbeat, name="heartbeat"),
    path('download_policy/', main_view.download_policy, name="download_policy"),
    path('api-token-auth/', views.obtain_auth_token)
]

app/core/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include  # add this

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path('yara_parser/', include('yara_parser.urls', namespace='yara_parser')),       
    path('api/', include('api.urls')),      
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")),             # UI Kits Html files
]

## remove this section of you are running standalone without a docker 
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
##################################################################### 

app/yara_parser/urls.py
from django.urls import path
from . import views

# URLConf
app_name="yara_parser"

urlpatterns = [
    # path('upload/', views.yara_parser),
    path('submit_upload/', views.submit_upload, name= "submit_upload"),
    path('file_upload/', views.yara_parser, name= "file_upload"),
    path('add_entity/', views.add_entity, name= "add_entity"),
]

app/yara_parser/models.py
from django.db import models
from django.db.models.fields import related
from django.conf import settings

# Create your models here.
class Entities (models.Model):
    entity_name = models.CharField(max_length=255, primary_key=True)
    cat_level = models.IntegerField(default=0)

class Scans (models.Model):
    upload_date = models.DateTimeField(auto_now_add=True)
    scan_date  = models.DateTimeField()
    host_name = models.CharField(max_length=255)
    drive_name = models.CharField(max_length=255)
    number_of_yara_scanned = models.IntegerField()
    is_admin = models.IntegerField()
    is_completed = models.IntegerField()
    number_of_alerts = models.IntegerField()
    number_of_warning = models.IntegerField()
    number_of_notices = models.IntegerField()
    file_base64 = models.TextField()
    added_by = models.CharField(max_length=255, default='N/A')
    processed_by  = models.CharField(max_length=255,default='Not_processed_yet')
    entity_name = models.ForeignKey(Entities, on_delete=models.CASCADE)
    scan_type = models.CharField(max_length=255, null=True)

    # def __str__(self) -> str:
    #     return self.entity_name


class file_scan (models.Model):
    TRIGGER_TYPES = [
        ('Warning', 'Warning'),
        ('Alert', 'Alert'),
        ('info', 'info'),
    ]

    INCEDENT_STATUS = [
        ('Pending', 'Pending'),
        ('Confirmed_incident', 'Confirmed_incident'),
        ('False_Positive', 'notice'),
    ]
    trigger_type = models.CharField(max_length=255, choices=TRIGGER_TYPES)
    modelue_type  = models.CharField(max_length=255)
    file_name = models.CharField(max_length=255)
    score = models.IntegerField()
    md5 = models.TextField()
    sha1 = models.TextField()
    sha256 = models.TextField()
    incident_status = models.CharField(max_length=255, choices=INCEDENT_STATUS, default='Pending')
    related_scan = models.ForeignKey(Scans, on_delete=models.CASCADE)
    analyst_comment = models.TextField(null=True)
    
class Process_Scan (models.Model):
    Process_TYPES = [
        ('Warning', 'Warning'),
        ('Alert', 'Alert'),
        ('info', 'info'),
    ]
    INCEDENT_STATUS = [
        ('Pending', 'Pending'),
        ('Confirmed_incident', 'Confirmed_incident'),
        ('False_Positive', 'notice'),
    ]
    process_inf_type = models.CharField(max_length=255, choices=Process_TYPES)
    process_name = models.CharField(max_length=255)
    process_path = models.TextField()
    cmd = models.TextField()
    owner = models.TextField()
    incident_status = models.CharField(max_length=255, choices=INCEDENT_STATUS, default='Pending')
    related_scan = models.ForeignKey(Scans, on_delete=models.CASCADE)
    analyst_comment = models.TextField(null=True)

class Reasons (models.Model):
    sub_score = models.IntegerField()
    reason = models.TextField()
    descreption = models.TextField()
    string_1 = models.TextField(null=True)
    string_2 = models.TextField(null=True)
    string_3 = models.TextField(null=True)
    realted_trigger = models.ForeignKey(file_scan, on_delete=models.CASCADE)


class client (models.Model):
    host_name = models.TextField()
    ip_add = models.TextField()
    mac_add = models.TextField()
    os = models.TextField()
    status = models.TextField()
    upload_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now_add=True)

class policy_scan (models.Model):
    name = models.TextField()
    path = models.TextField()
    link = models.TextField()
    descreption = models.TextField()

class schedualled_scan (models.Model):
    policy_name = models.TextField()
    target_machine = models.TextField()
    target_mac = models.TextField()
    status = models.TextField()

app/yara_parser/views.py
import base64
from datetime import datetime
import re
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.messages.storage.base import Message
from yara_parser.models import Entities, Process_Scan, Reasons, Scans, file_scan, client,schedualled_scan
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from rest_framework.authtoken.models import Token

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}


@login_required(login_url="/login/")
def yara_parser(request):
    # Getting the Entity Names for the drop down list. 
    QuerySet =  Entities.objects.all().order_by('entity_name') 
    return render(request, 'file-upload.html', {'entities' : list(QuerySet)})

@login_required(login_url="/login/")
def submit_upload(request): # this function will cover the parsing of a newlly updated yara results into the database.. 

    if(request.POST.get('upload_button')): # checking if the button was clicked.

        # Reading the results and parsing them into the database.
        files = request.FILES.getlist('yara_results')
        entity_name  = request.POST.get('entites')
        scan_type  = "Yara_station"

        print (files)     

        for file in files:# looping through all the uploaded files.          
            if (file.name).endswith('.txt') or (file.name).endswith('.log'):
                try:
                    parse_txt (file, entity_name,scan_type, request)
                except:
                    messages.error(request, "Appolgies, There was an error uploading file (" +file.name + "). if the file was generated using Loki scanner please open and issue in the github page. NOTE: other tools (e.g. thor) are not supported yet ")

            elif (file.name).endswith('.CSV') or (file.name).endswith('.csv'):
                try:
                    parse_csv (file, entity_name,scan_type, request)
                except:
                    messages.error(request, "Appolgies, There was an error uploading file (" +file.name + "). if the file was generated using Loki scanner please open and issue in the github page. NOTE: other tools (e.g. thor) are not supported yet ")
        
        # finishing the function and redirecting the user to the success page..
        # Getting the Entity Names for the drop down list. 
        QuerySet =  Entities.objects.all().order_by('entity_name') 

        return render(request, 'file-upload.html', {'entities' : list(QuerySet)})

    else:
        # finishing the function and redirecting the user to the success page..
        # Getting the Entity Names for the drop down list. 
        QuerySet =  Entities.objects.all().order_by('entity_name') 
        return render(request, 'file-upload.html', {'entities' : list(QuerySet)})

def parse_txt (file, entity_name,sc_type, request): #function for parsing txt files. 

    # check the source of the upload (from GUI or API)
    if not(isinstance(file, bytes)):
        print ("<< GUI upload >>")
        content_bytes = file.read()

    else:
        print ("<< API upload >>")
        content_bytes = file

    # intilizing the variables.
    #-----------------
    # converting the document to base64 
    base64_bytes = base64.b64encode(content_bytes)
    base64_content = base64_bytes.decode('ascii')

    # converting content to string for processing
    content_string = content_bytes.decode('ascii')
    
    # Extracting the content.
    #-----------------

    #splited_content_string = content_string.split('\n')

    # Extracting if the program ran as an administrator
    admin_not_found = content_string.find("Program should be run 'as Administrator'")
    if admin_not_found == -1:
        is_admin = 1
    else:
        is_admin = 0

    # Extracting if the scan is complete
    complete_found = content_string.find("Finished LOKI Scan")
    if complete_found == -1:
        is_complete = 0
    else:
        is_complete=1
    
    # Extracting scan date and host_name
    substring = re.search('SYSTEM: (.+?) TIME: (.+?) ', content_string)
    if substring is None: # if one of them is missing?
        host_name = "N/A"
        scan_date = None
    else:
        host_name = substring.group(1)
        scan_date = datetime.strptime(substring.group(2), '%Y%m%dT%H:%M:%SZ')
        print (scan_date)

    # Extracting the scanned drive
    if content_string.find("Info: MODULE: FileScan MESSAGE: Scanning") != -1:
        drive = re.split('Info: MODULE: FileScan MESSAGE: Scanning ', content_string)
        drive.remove(drive[0])
        drive=drive[0]
        drive=drive[:drive.find("\n")-1]
        if drive.find("Path")!=-1:
            drive= drive[drive.find("Path")+5:]
    else:
        drive = "N/A"

    # Extracting number of yara rules scanned.
    substring = re.search('Initialized (.+?) Yara rules', content_string)
    if substring is None:
        yara_rules_number = 0 
    else:
        yara_rules_number = int(substring.group(1))

    # Extracting alerts, warnings, notices
    substring = re.search('Results: (.+?) alerts.+? (.+?) warnings.+? (.+?) notices', content_string)
    if substring is None:
        alerts = 0
        warnings = 0
        notices = 0
    else:
        alerts=int(substring.group(1))
        warnings=int(substring.group(2))
        notices=int(substring.group(3)) 


    # print ("---------------Testing Block--------------------\n\n")
    # print ("date:", scan_date)
    # print ("entity_name:", entity_name)
    # print ("host_name:", host_name)
    # print ("yara_rules_number:", yara_rules_number)
    # print ("is_admin:", is_admin)
    # print ("alerts:", alerts)
    # print ("warnings:", warnings)
    # print ("notices:", notices)
    # print ("is_complete:", is_complete)
    # print ("-----------------------------------\n\n")


    # Creating the scan object
    new_scan = Scans()
    new_scan.scan_date = scan_date
    new_scan.entity_name = Entities(entity_name)
    new_scan.host_name = host_name
    new_scan.is_admin = is_admin
    new_scan.is_completed = is_complete
    new_scan.number_of_yara_scanned = yara_rules_number
    new_scan.number_of_alerts = alerts
    new_scan.number_of_notices = notices
    new_scan.number_of_warning = warnings
    new_scan.file_base64 = base64_content
    new_scan.added_by = request.user.username
    new_scan.drive_name = drive
    new_scan.scan_type = sc_type

    # inserting scan information to database.
    new_scan.save() 
    
    messages.success(request, "Record has been updated successfully...")

    #-----------------------------------------------------------------------------------------------------------------------
    #       At this point the scan infomration is added to the DB, now we check if there is any results to register. 
    #-----------------------------------------------------------------------------------------------------------------------
    
    if alerts > 0 or warnings > 0:
      
        # split the content of the file by rows to get each alert by itself. 
        splited_content_string = content_string.split('\n')
        
        for line in splited_content_string:

            if line.find("LOKI: Alert: MODULE: FileScan") != -1 or line.find("LOKI: Warning: MODULE: FileScan") != -1 :  

                if line.find("LOKI: Alert: MODULE: FileScan") != -1: # filescan alert was found
                    print("******************FILESCAN ALERT************************")    
                    alert_type = "Alert"
                    alert_module = "FileScan"
                    
                elif line.find("LOKI: Warning: MODULE: FileScan") != -1: # filescan Warning was found
                    print("******************FILESCAN warning************************")
                    alert_type = "Warning"
                    alert_module = "FileScan"

                #Extract filename
                substring = re.search('FILE: (.+?) SCORE:', line)
                if substring is None:
                    filename = "N/A"
                else:
                    filename = substring.group(1)

                #Extract score
                substring = re.search('SCORE: (.+?) ', line)
                if substring is None:
                    score = 0
                else:
                    score = int(substring.group(1)) 
                
                #Extract MD5                       
                substring = re.search('MD5: (.+?) ', line)
                if substring is None:
                    MD5="N/A"
                else:
                    MD5=substring.group(1)

                    
                #Extract SHA1                        
                substring = re.search('SHA1: (.+?) ', line)
                if substring is None:
                    SHA1="N/A"
                else:
                    SHA1=substring.group(1)

                #Extract SHA256                        
                substring = re.search('SHA256: (.+?) ', line)
                if substring is None:
                    SHA256="N/A"
                else:
                    SHA256=substring.group(1)

                # Testing Block
                # print("_________________Alert Info_________________")
                # print("type:",type)
                # print("module:",module)
                # print("filename:",filename)
                # print("score:",score)

                # print("MD5:",MD5)
                # print("SHA1:",SHA1)
                # print("SHA256:",SHA256)
                # print("__________________________________________\n")

                # Creating the Trigger object
                new_trigger = file_scan()
                new_trigger.modelue_type = alert_module
                new_trigger.trigger_type = alert_type
                new_trigger.file_name = filename
                new_trigger.score = score
                new_trigger.md5 = MD5

app/yara_parser/templates/file-upload.html
{% extends "layouts/base.html" %}

{% block title %} File Upload {% endblock %} 

{% block stylesheets %}
    {% load static %}
    <!-- fileupload-custom css -->
    <link rel="stylesheet" href="{% static 'assets/css/pages/fileupload.css' %} ">

    <link rel="stylesheet" href="{% static 'assets/plugins/modal-window-effects/css/md-modal.css' %}">

     <!-- select2 css -->
     <link rel="stylesheet" href="{% static 'assets/plugins/select2/css/select2.min.css' %}">
     <!-- multi-select css -->
     <link rel="stylesheet" href="{% static 'assets/plugins/multi-select/css/multi-select.css' %} ">
     

{% endblock stylesheets %}

{% block content %}



    <!-- [ Main Content ] start -->
    <section class="pcoded-main-container">
        <div class="pcoded-wrapper">
            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->
                    <div class="page-header">
                        <div class="page-block">
                            <div class="row align-items-center">
                                <div class="col-md-12">
                                    <div class="page-header-title">
                                        <h5 class="m-b-10">File Upload</h5>
                                    </div>
                                    <ul class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                                        <li class="breadcrumb-item"><a href="#!">File Upload</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <!-- [ file-upload ] start -->
                                <div class="col-sm-12">
                                    <div class="card">
                                        
                                        <div class="card-header">
                                            <h5>File Upload</h5>
                                        </div>

                                        <div id="content-wrapper" class="d-flex flex-column">
                                            {% for message in messages %}
                                                <div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert"> {{message}}</div>
                                            {% endfor %}
                                        </div>

                                        <div class="card-block">
                                            <form action="{% url 'yara_parser:submit_upload' %}" method="POST" enctype="multipart/form-data" onsubmit="toggleupload()"> {% csrf_token %}
                                                <div class="col-xl-4 col-md-6 mb-5">
                                                    <h5>Entity Name <i><sub>  ** Used to identify target groups e.g. multiple sites </sub></i></h5>
                                                    <hr>
                                                    <p>Select related entity from the list or <a href="#" data-toggle="modal" data-target="#exampleModal" >add new entity </a> </p>
                                                    <select name="entites" id="entites" required="required" class="js-example-placeholder-multiple col-sm-12" >
                                                        <option> </option>
                                                        {% for entity in entities %}
                                                            <option value="{{ entity.entity_name }}" > {{ entity.entity_name }} </option> 
                                                        {% endfor %}
                                                    </select>
                                                    <br/>
                                                    <br/>
                                                    <hr>
                                                    

                                                    <input type="file" name="yara_results" id="yara_results" required="required" multiple="multiple" accept=".csv,.txt,.log" />
                                                    <label for="files"><span>The parser only accepts (.txt .log .csv) formats</span></label>
                                                    
                                                </div>
                                                
                                                <div class="text-center m-t-20">
                                                    <button id="submit12" type="submit" value="Click" name="upload_button" class="btn btn-primary" >Upload Results</button>
                                                    <div id="spinner" class="spinner-border" role="status" style="visibility: hidden">
                                                        <span  class="sr-only" >Loading...</span>
                                                    </div>
                                                </div> 
                                            </form>
                                            
                                        </div>
                                    </div>
                                </div>
                                <!-- [ file-upload ] end -->
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- [ Main Content ] end -->



    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Entity</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <form action="{% url 'yara_parser:add_entity'%}" method="POST" > {% csrf_token %} 
                    <div class="modal-body">
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Entity Name: <i><sub> ** Used to identify target groups e.g. multiple sites </i></sub> </label>
                                <input type="text" class="form-control" id="recipient-name" name="recipient-name" required="required">
                            </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn notifications btn-success" data-type="success" data-from="top" data-align="right">success</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>   
            </div>
        </div>
    </div>


{% endblock content %}

{% block javascripts %}

    {% load static %}
    <!-- file-upload Js -->
    <script src="{% static 'assets/plugins/fileupload/js/dropzone-amd-module.min.js' %}"></script>

    <!-- modal-window-effects Js -->
    <script src="{% static 'assets/plugins/modal-window-effects/js/classie.js' %}"></script>
    <script src="{% static 'assets/plugins/modal-window-effects/js/modalEffects.js' %} "></script>

    <!-- select2 Js -->
    <script src="{% static 'assets/plugins/select2/js/select2.full.min.js' %}"></script>

    <!-- multi-select Js -->
    <script src="{% static 'assets/plugins/multi-select/js/jquery.quicksearch.js' %}"></script>
    <script src="{% static 'assets/plugins/multi-select/js/jquery.multi-select.js' %}"></script>

    <!-- form-select-custom Js -->
    <script src="{% static 'assets/js/pages/form-select-custom.js' %}"></script>

    <!-- sweet alert Js -->
    <script src="{% static 'assets/plugins/sweetalert/js/sweetalert.min.js' %}"></script>
    <script src="{% static 'assets/js/pages/ac-alert.js' %}"></script>


    <script type="text/javascript">
        function toggleupload(){
                document.getElementById('spinner').style.visibility = 'visible';
                document.getElementById('submit12').innerText= "Loading";
        }
    </script>
    <script>
        $('#exampleModal').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var recipient = button.data('whatever') // Extract info from data-* attributes
            var modal = $(this)
            modal.find('.modal-title').text('New message to ' + recipient)
            modal.find('.modal-body input').val(recipient)
        })
    </script>

    <!-- Notification css -->
    <link href="/static/assets/plugins/notification/css/notification.min.css" rel="stylesheet">
    <!-- Notification Js -->
    <script src="/static/assets/plugins/notification/js/bootstrap-growl.min.js"></script>

{% endblock javascripts %}